backend:
  name: git-gateway
  branch: main
media_folder: src/public/images/uploads
public_folder: /images/uploads
collections:
  - name: content
    label: Content
    files:
      - name: links
        label: Links
        file: src/_data/links.json
        fields:
          - name: links
            label: Links
            widget: list
            fields:
              - name: name
                label: Name
                widget: string
              - name: url
                label: URL
                widget: string
